---
# tasks file for user_settings


- name: add public key file
  copy:
    path: ~/.ssh/id_rsa.pub
    content: "{{ssh_key}}"
    mode: '0644'

- name: Create user
  user:
    name: "{{username}}"
    password: "{{ password | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: on_create



