---
# tasks file for user_settings



- name: Create user
  user:
    name: "{{username}}"
    password: "{{ password | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: on_create

- name: add public key file
  become: yes
  file:
    state: touch
    path: ~/.ssh/id_rsa.pub
    content: "{{ssh_key}}"
    owner: "{{username}}"
    group: "{{username}}"
    mode: '0644'
